version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "go/"
    schedule:
      interval: "monthly"
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directories:
      - "terraform/modules/gce"
      - "terraform/modules/google_project_services"
      - "terraform/modules/tfstate_gcs_bucket"
      - "terraform/environments/dev"
    schedule:
      interval: "monthly"
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
