// Code generated by MockGen. DO NOT EDIT.
// Source: vm_repository.go
//
// Generated by this command:
//
//	mockgen -source=vm_repository.go -destination=../../mock/repository/vm_repository_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/haru-256/gcectl/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockVMRepository is a mock of VMRepository interface.
type MockVMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVMRepositoryMockRecorder
	isgomock struct{}
}

// MockVMRepositoryMockRecorder is the mock recorder for MockVMRepository.
type MockVMRepositoryMockRecorder struct {
	mock *MockVMRepository
}

// NewMockVMRepository creates a new mock instance.
func NewMockVMRepository(ctrl *gomock.Controller) *MockVMRepository {
	mock := &MockVMRepository{ctrl: ctrl}
	mock.recorder = &MockVMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMRepository) EXPECT() *MockVMRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockVMRepository) FindAll(ctx context.Context) ([]*model.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*model.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockVMRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockVMRepository)(nil).FindAll), ctx)
}

// FindByName mocks base method.
func (m *MockVMRepository) FindByName(ctx context.Context, vm *model.VM) (*model.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, vm)
	ret0, _ := ret[0].(*model.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockVMRepositoryMockRecorder) FindByName(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockVMRepository)(nil).FindByName), ctx, vm)
}

// SetSchedulePolicy mocks base method.
func (m *MockVMRepository) SetSchedulePolicy(ctx context.Context, vm *model.VM, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSchedulePolicy", ctx, vm, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSchedulePolicy indicates an expected call of SetSchedulePolicy.
func (mr *MockVMRepositoryMockRecorder) SetSchedulePolicy(ctx, vm, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSchedulePolicy", reflect.TypeOf((*MockVMRepository)(nil).SetSchedulePolicy), ctx, vm, policyName)
}

// Start mocks base method.
func (m *MockVMRepository) Start(ctx context.Context, vm *model.VM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockVMRepositoryMockRecorder) Start(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVMRepository)(nil).Start), ctx, vm)
}

// Stop mocks base method.
func (m *MockVMRepository) Stop(ctx context.Context, vm *model.VM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockVMRepositoryMockRecorder) Stop(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVMRepository)(nil).Stop), ctx, vm)
}

// UnsetSchedulePolicy mocks base method.
func (m *MockVMRepository) UnsetSchedulePolicy(ctx context.Context, vm *model.VM, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetSchedulePolicy", ctx, vm, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsetSchedulePolicy indicates an expected call of UnsetSchedulePolicy.
func (mr *MockVMRepositoryMockRecorder) UnsetSchedulePolicy(ctx, vm, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetSchedulePolicy", reflect.TypeOf((*MockVMRepository)(nil).UnsetSchedulePolicy), ctx, vm, policyName)
}

// UpdateMachineType mocks base method.
func (m *MockVMRepository) UpdateMachineType(ctx context.Context, vm *model.VM, machineType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineType", ctx, vm, machineType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMachineType indicates an expected call of UpdateMachineType.
func (mr *MockVMRepositoryMockRecorder) UpdateMachineType(ctx, vm, machineType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineType", reflect.TypeOf((*MockVMRepository)(nil).UpdateMachineType), ctx, vm, machineType)
}
