# TODO: Add more linters
# https://gist.githubusercontent.com/maratori/47a4d00457a92aa426dbd48a18776322/raw/43d6de07ca238a3994737171bd3fe2cd2b769bc0/.golangci.yml

version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace

  settings:
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    gocyclo:
      min-complexity: 30
    misspell:
      locale: US

  exclusions:
    rules:
      # テストファイルにだけ適用する除外規則
      - path: _test\.go$
        linters:
          - govet
        text: "fieldalignment: struct with" # 警告メッセージでマッチ

formatters:
  enable:
    - goimports
    - gofmt
