default-project: haru256-sandbox-20250225
default-zone: us-central1-a
vm:
  - name: sandbox
    project: haru256-sandbox-20250225
    zone: us-central1-a
  # - name: haru256-gpu
  #   project: haru256-sandbox-20250224
  #   zone: asia-northeast1-a
