// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source=session.go -destination=../../mock/interface/cli/session_mock.go -package=mock_cli
//

// Package mock_cli is a generated GoMock package.
package mock_cli

import (
	context "context"
	reflect "reflect"

	model "github.com/haru-256/gcectl/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockVMRepositoryCloser is a mock of VMRepositoryCloser interface.
type MockVMRepositoryCloser struct {
	ctrl     *gomock.Controller
	recorder *MockVMRepositoryCloserMockRecorder
	isgomock struct{}
}

// MockVMRepositoryCloserMockRecorder is the mock recorder for MockVMRepositoryCloser.
type MockVMRepositoryCloserMockRecorder struct {
	mock *MockVMRepositoryCloser
}

// NewMockVMRepositoryCloser creates a new mock instance.
func NewMockVMRepositoryCloser(ctrl *gomock.Controller) *MockVMRepositoryCloser {
	mock := &MockVMRepositoryCloser{ctrl: ctrl}
	mock.recorder = &MockVMRepositoryCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMRepositoryCloser) EXPECT() *MockVMRepositoryCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVMRepositoryCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockVMRepositoryCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVMRepositoryCloser)(nil).Close))
}

// FindByName mocks base method.
func (m *MockVMRepositoryCloser) FindByName(ctx context.Context, vm *model.VM) (*model.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, vm)
	ret0, _ := ret[0].(*model.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockVMRepositoryCloserMockRecorder) FindByName(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockVMRepositoryCloser)(nil).FindByName), ctx, vm)
}

// SetSchedulePolicy mocks base method.
func (m *MockVMRepositoryCloser) SetSchedulePolicy(ctx context.Context, vm *model.VM, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSchedulePolicy", ctx, vm, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSchedulePolicy indicates an expected call of SetSchedulePolicy.
func (mr *MockVMRepositoryCloserMockRecorder) SetSchedulePolicy(ctx, vm, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSchedulePolicy", reflect.TypeOf((*MockVMRepositoryCloser)(nil).SetSchedulePolicy), ctx, vm, policyName)
}

// Start mocks base method.
func (m *MockVMRepositoryCloser) Start(ctx context.Context, vm *model.VM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockVMRepositoryCloserMockRecorder) Start(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVMRepositoryCloser)(nil).Start), ctx, vm)
}

// Stop mocks base method.
func (m *MockVMRepositoryCloser) Stop(ctx context.Context, vm *model.VM) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockVMRepositoryCloserMockRecorder) Stop(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVMRepositoryCloser)(nil).Stop), ctx, vm)
}

// UnsetSchedulePolicy mocks base method.
func (m *MockVMRepositoryCloser) UnsetSchedulePolicy(ctx context.Context, vm *model.VM, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetSchedulePolicy", ctx, vm, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsetSchedulePolicy indicates an expected call of UnsetSchedulePolicy.
func (mr *MockVMRepositoryCloserMockRecorder) UnsetSchedulePolicy(ctx, vm, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetSchedulePolicy", reflect.TypeOf((*MockVMRepositoryCloser)(nil).UnsetSchedulePolicy), ctx, vm, policyName)
}

// UpdateMachineType mocks base method.
func (m *MockVMRepositoryCloser) UpdateMachineType(ctx context.Context, vm *model.VM, machineType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineType", ctx, vm, machineType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMachineType indicates an expected call of UpdateMachineType.
func (mr *MockVMRepositoryCloserMockRecorder) UpdateMachineType(ctx, vm, machineType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineType", reflect.TypeOf((*MockVMRepositoryCloser)(nil).UpdateMachineType), ctx, vm, machineType)
}
