name: go-lint
on:
  push:
    branches:
      - main
    paths:
      - "go/**.go"
      - ".github/workflows/go-lint.yml"
  pull_request:
    paths:
      - "go/**.go"
      - ".github/workflows/go-lint.yml"
jobs:
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: ls
        run: ls -Ra
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          go_version_file: "./go/go.mod" # this should be relative to the root of the repository
          fail_level: "error"
          reporter: "github-pr-review"
          workdir: "./go"
